# pore_bvp_joint.py
import pyomo.environ as pyo
from .utils import get_enzyme_profile_rule, get_enzyme_decay_rule, get_enzyme_kinetics, calculate_pore_count_coefficient

def add_bvp_constraints(model, immobilization='co-immobilization', decay_coef={'kA':0, 'kB':0}, bvp_kwargs=None): 
    if bvp_kwargs is None:
        bvp_kwargs = {}
        
    # --- 1. Extract Enzyme-Specific Settings ---
    default_fun    = bvp_kwargs.get('default_fun', 'linear')
    enzymeA_kwargs = bvp_kwargs.get('enzymeA', {})
    enzymeB_kwargs = bvp_kwargs.get('enzymeB', {})
    
    # INDEPENDENT KINETIC TYPES
    kinetics_type_A = enzymeA_kwargs.get('kinetics_type', 'first_order')
    kinetics_type_B = enzymeB_kwargs.get('kinetics_type', 'first_order')
    
    # Safely extract dimensional reference constants (S_ref=1.0 for dimensional 'S')
    Km_A  = getattr(model, 'kM_A', None) 
    Km_B  = getattr(model, 'kM_B', None)

    # --- 2. Create symbolic enzyme decay profiles ---
    model.decay_A = pyo.Expression(model.time, rule=get_enzyme_decay_rule(decay_coef.get('kA', 0.0)))
    model.decay_B = pyo.Expression(model.time, rule=get_enzyme_decay_rule(decay_coef.get('kB', 0.0)))
     
    # Enzyme A profile. 
    model.EA_x_profile = get_enzyme_profile_rule(
        model, model.EA_max,
        start=enzymeA_kwargs.get('start', 1), end=enzymeA_kwargs.get('end', 0),
        fun=enzymeA_kwargs.get('fun', default_fun),
        **{k: v for k, v in enzymeA_kwargs.items() if k not in ['fun', 'start', 'end', 'kinetics_type']}
    )
    # Enzyme B profile. 
    model.EB_x_profile = get_enzyme_profile_rule(
        model, model.EB_max,
        start=enzymeB_kwargs.get('start', 0), end=enzymeB_kwargs.get('end', 1),
        fun=enzymeB_kwargs.get('fun', default_fun),
        **{k: v for k, v in enzymeB_kwargs.items() if k not in ['fun', 'start', 'end', 'kinetics_type']}
    )

    # --- ODE system --- 
    def S1_mixed_pore_bvp_rule(m, x, t):
        lhs_A, rhs_A = get_enzyme_kinetics(
            m.EA_x_profile[x], m.decay_A[t], m.kA, m.S_n['S1', x, t],
            Km=Km_A, kinetics_type=kinetics_type_A
        )
        return lhs_A * m.D['S1'] * m.d2S_ndx2['S1', x, t] == rhs_A
    model.S1_mixed_pore_bvp = pyo.Constraint(model.x, model.time, rule=S1_mixed_pore_bvp_rule)  
            
    # S2: Generated by Enzyme A, Consumed by Enzyme B
    def S2_mixed_pore_bvp_rule(m, x, t):
        lhs_A, rhs_A = get_enzyme_kinetics(
            m.EA_x_profile[x], m.decay_A[t], m.kA, m.S_n['S1', x, t],
            Km=Km_A, kinetics_type=kinetics_type_A
        )
        lhs_B, rhs_B = get_enzyme_kinetics(
            m.EB_x_profile[x], m.decay_B[t], m.kB, m.S_n['S2', x, t],
            Km=Km_B, kinetics_type=kinetics_type_B
        )
        return (lhs_A * lhs_B) * m.D['S2'] * m.d2S_ndx2['S2', x, t] == (lhs_A * rhs_B) - (lhs_B * rhs_A)
    model.S2_mixed_pore_bvp = pyo.Constraint(model.x, model.time, rule=S2_mixed_pore_bvp_rule)
    
    def S3_mixed_pore_bvp_rule(m, x, t):
        lhs_B, rhs_B = get_enzyme_kinetics(
            m.EB_x_profile[x], m.decay_B[t], m.kB, m.S_n['S2', x, t],
            Km=Km_B, kinetics_type=kinetics_type_B
        )
        return lhs_B * m.D['S3'] * m.d2S_ndx2['S3', x, t] == -rhs_B
    model.S3_mixed_pore_bvp = pyo.Constraint(model.x, model.time, rule=S3_mixed_pore_bvp_rule)        
    
    # --- Boundary conditions ---
    def bc1_rule(m, component, t):
        return m.S_n[component, m.x.first(), t] == m.S_0[component,t]
    model.bc1 = pyo.Constraint(model.Components, model.time, rule=bc1_rule)
    
    def bc2_rule(m, component, t):
        return m.dS_ndx[component, m.x.last(), t] == 0
    model.bc2 = pyo.Constraint(model.Components, model.time, rule=bc2_rule)
    
    # Flux expression (used in reactor ODE)    
        
    if bvp_kwargs.get('adjust_Np', False):
        pore_count_coef = calculate_pore_count_coefficient(
            model, 
            model.EA_x_profile, model.EB_x_profile,
            model.EA_max/2, model.EB_max/2)
    else:
        pore_count_coef = 1.0
        
    def flux_rule(m, component, t):
        return -m.D[component] * m.dS_ndx[component, m.x.first(), t] * m.A * m.Np * pore_count_coef
    model.flux = pyo.Expression(model.Components, model.time, rule=flux_rule)