# pore_bvp_co_immobilization.py
import pyomo.environ as pyo
from .utils import get_enzyme_profile_rule, get_enzyme_decay_rule, get_enzyme_kinetics, calculate_pore_count_coefficient

def add_bvp_constraints(model, decay_coef={'kA':0, 'kB':0}, bvp_kwargs=None): 
    if bvp_kwargs is None:
        bvp_kwargs = {}
        
    # --- 1. Extract Enzyme-Specific Settings ---
    default_fun    = bvp_kwargs.get('default_fun', 'linear')
    enzymeA_kwargs = bvp_kwargs.get('enzymeA', {})
    enzymeB_kwargs = bvp_kwargs.get('enzymeB', {})
    
    # INDEPENDENT KINETIC TYPES
    kinetics_type_A = enzymeA_kwargs.get('kinetics_type', 'first_order')
    kinetics_type_B = enzymeB_kwargs.get('kinetics_type', 'first_order')
    
    # Safely extract reference constants (Required if MM is chosen for either)
    S_ref = getattr(model, 'S_ref', 1.0)
    Km_A  = getattr(model, 'kM_A', None) 
    Km_B  = getattr(model, 'kM_B', None)

    # --- 2. Create symbolic enzyme decay profiles ---
    model.decay_A = pyo.Expression(model.time, rule=get_enzyme_decay_rule(decay_coef.get('kA', 0.0)))
    model.decay_B = pyo.Expression(model.time, rule=get_enzyme_decay_rule(decay_coef.get('kB', 0.0)))

    # --- 3. Build enzyme density profile along the shared pore ---
    model.EA_x_profile = get_enzyme_profile_rule(
        model, model.EA_max,
        start=enzymeA_kwargs.get('start', 0.5), end=enzymeA_kwargs.get('end', 0.5),
        fun=enzymeA_kwargs.get('fun', default_fun),
        **{k: v for k, v in enzymeA_kwargs.items() if k not in ['fun', 'start', 'end', 'kinetics_type']}
    )
    
    model.EB_x_profile = get_enzyme_profile_rule(
        model, model.EB_max,
        start=enzymeB_kwargs.get('start', 0.5), end=enzymeB_kwargs.get('end', 0.5),
        fun=enzymeB_kwargs.get('fun', default_fun),
        **{k: v for k, v in enzymeB_kwargs.items() if k not in ['fun', 'start', 'end', 'kinetics_type']}
    )

    # --- 4. BVP PDEs (Both enzymes in the same pore) ---
    
    # S1 PDE: Consumed by Enzyme A
    def S1_mixed_pde_rule(m, xi, t): 
        lhs_A, rhs_A = get_enzyme_kinetics(
            m.EA_x_profile[xi], m.decay_A[t], m.kA, m.u_n['S1', xi, t],
            S_ref=S_ref, Km=Km_A, kinetics_type=kinetics_type_A
        )
        return lhs_A * (m.D['S1'] / m.L**2) * m.d2u_ndxi2['S1', xi, t] == rhs_A
    model.S1_pde = pyo.Constraint(model.xi, model.time, rule=S1_mixed_pde_rule)

    # S2 PDE: Generated by Enzyme A, Consumed by Enzyme B
    # Cross-multiplication trick: (LHS_A * LHS_B) * D * d2u = (LHS_A * RHS_B) - (LHS_B * RHS_A)
    def S2_mixed_pde_rule(m, xi, t): 
        lhs_A, rhs_A = get_enzyme_kinetics(
            m.EA_x_profile[xi], m.decay_A[t], m.kA, m.u_n['S1', xi, t],
            S_ref=S_ref, Km=Km_A, kinetics_type=kinetics_type_A
        )
        lhs_B, rhs_B = get_enzyme_kinetics(
            m.EB_x_profile[xi], m.decay_B[t], m.kB, m.u_n['S2', xi, t],
            S_ref=S_ref, Km=Km_B, kinetics_type=kinetics_type_B
        )
        return (lhs_A * lhs_B) * (m.D['S2'] / m.L**2) * m.d2u_ndxi2['S2', xi, t] == (lhs_A * rhs_B) - (lhs_B * rhs_A)
    model.S2_pde = pyo.Constraint(model.xi, model.time, rule=S2_mixed_pde_rule)

    # S3 PDE: Generated by Enzyme B
    def S3_mixed_pde_rule(m, xi, t): 
        lhs_B, rhs_B = get_enzyme_kinetics(
            m.EB_x_profile[xi], m.decay_B[t], m.kB, m.u_n['S2', xi, t],
            S_ref=S_ref, Km=Km_B, kinetics_type=kinetics_type_B
        )
        return lhs_B * (m.D['S3'] / m.L**2) * m.d2u_ndxi2['S3', xi, t] == -rhs_B
    model.S3_pde = pyo.Constraint(model.xi, model.time, rule=S3_mixed_pde_rule)

    # --- 5. Shared Boundary Conditions --- 
    # Rule #1: Substrate conc. at pore mouth (xi=0) equals bulk concentration
    def bc1_rule(m, component, t):
        return m.u_n[component, m.xi.first(), t] == m.u_0[component, t]
    model.bc1 = pyo.Constraint(model.Components, model.time, rule=bc1_rule)

    # Rule #2: Zero flux at pore dead-end (xi=1)
    def bc2_rule(m, component, t):
        return m.du_ndxi[component, m.xi.last(), t] == 0
    model.bc2 = pyo.Constraint(model.Components, model.time, rule=bc2_rule)

    # --- 6. Flux expression for the reactor IVP --- 
    # Calculate pore count modifier if we want to ensure total enzyme mass equals the single-immobilization baseline
    if bvp_kwargs.get('adjust_Np', False):
        pore_count_coef = calculate_pore_count_coefficient(
            model, 
            model.EA_x_profile, model.EB_x_profile,
            model.EA_max/2, model.EB_max/2
        )
    else:
        pore_count_coef = 1.0

    def flux_rule(m, component, t):
        # Flux out of the single shared pore, multiplied by modified pore count
        return -m.D[component] * (m.S_ref / m.L) * m.du_ndxi[component, m.xi.first(), t] * m.A * m.Np * pore_count_coef
        
    model.flux = pyo.Expression(model.Components, model.time, rule=flux_rule)